### ISSUE TITLE
Order error with numbers

### ISSUE THREAD

**Issue by darkmarcos** [kzhovn/file-explorer-keyboard-nav#1]
I'm with a problem when I try to use the plugin with notes with numbering. Below is an example, instead of following "1, 2, 3, 4, 5" it is following "1, 10, 100, 1000, 1001, etc.".

Actual note: 
![image](https://user-images.githubusercontent.com/87239997/172024574-a83177f4-9a45-4ebe-a208-c35d03cd7314.png)

Next note after pressing the key Ctrl + ↓:
![image](https://user-images.githubusercontent.com/87239997/172024563-2eb4b25e-448a-4cc4-9a35-da0ef4e7d1d0.png)

**Comment by kzhovn** [comment]
Interesting, and thank you for the bug report! When I have files named `Untitled 1` through `Untitled 11`, the jumping doesn't happen, but `Untitled Nº 0` through `Untitled Nº 11` jumps from 0 to 2, and then moves correctly through those files. The order it seems to think my files are in are `all the other files -> Untitled Nº 1 -> Untitled Nº 0 -> Untitled Nº 2 -> the rest of the Untitled Nº s in order`. If I change to a lowercase "n", it cycles in order, though it still thinks that these files are below all of the other files in this folder. I have no clue what could be causing this kind of ordering, honestly.

Can you copy and paste exactly what you have for your title? I'd like to be able to replicate it and I'm thinking we might be using slightly different special characters or something like that.

**Comment by kzhovn** [comment]
Ah, mea culpa, the files loaded at inconsistent times; now I can replicate the same jump you're getting.

**Comment by kzhovn** [comment]
@darkmarcos the [new release](https://github.com/kzhovn/file-explorer-keyboard-nav/releases/tag/0.2.0) fixes a bunch of sorting issues including, hopefully, this one. Let me know if you have any further problems!
